#ifndef DEMCONSTANTS_H
#define DEMCONSTANTS_H

#ifdef LIQ_DEM
#ifdef LINEAR
const double DEM_TIMESTEP = (1.0/50.0)*PI/sqrt(DEM_K/DEM_MIN_REDUCED_MASS-pow(0.5*DEM_GAMMA/DEM_MIN_REDUCED_MASS,2));
#endif
#ifdef LUBRICATION
const double DEM_REDUCED_MASS = DEM_MIN_REDUCED_MASS;
const double DEM_REDUCED_RADIUS = DEM_RADIUS/2.0;
const double DEM_SEARCH_RADIUS = 1.0*DEM_RADIUS + DEM_REDUCED_RADIUS;
const double LUB_GAMMA = 6.0*PI*VISCOSITY*DENS*DEM_REDUCED_RADIUS/(ROUGHNESS_EPSILON*(1-ROUGHNESS_EPSILON));
const double DEM_TIMESTEP = (1.0/50.0)*PI/sqrt(DEM_K/DEM_MIN_REDUCED_MASS-pow(0.5*LUB_GAMMA/DEM_MIN_REDUCED_MASS,2));
#else
const double DEM_SEARCH_RADIUS = 1.0*DEM_RADIUS;
#endif


const double LIQ_DEM_TIMESTEP = (1.0/5.0)*DEM_VOL*DEM_DENS/(6.0*PI*VISCOSITY*DENS*DEM_RADIUS);
#endif


//const int TWIN_N = LIQ_DEM_TWIN/DEM_TIMESTEP;
const int TWIN_N = 2;
 
#endif
